### ISSUE TITLE
[solved] no_std Can't find crate for 'test'

### ISSUE THREAD

**Issue by bathtimefish** [doraneko94/rp_pico_template#1]
I'm using rust-analyzer extension in VSCode. I had an error of `no_std Can't find crate for 'test'` in the top of line when I opened `src/led.rs`.

So I add some properties for rust-analyzer in `.vscode/setting.json`, It solved it.

```.vscode/settings.json
{
    "rust.target": "thumbv6m-none-eabi",
    "rust.all_targets": false,
    "rust-analyzer.cargo.target": "thumbv6m-none-eabi",
    "rust-analyzer.checkOnSave": false
}
```

I'm happy if you can use that as a reference.

**Comment by doraneko94** [comment]
Thank you very much!
I updated `.vscode/setting.json`.
